### ISSUE TITLE
Issue in the data_pro.py affecting train-test split logic 

### ISSUE THREAD

**Issue by YYYYYUYAN** [Oia-10/PSKT#1]
Hello,  

Thank you for contributing this code—it has been very helpful.

There is an issue in the data processing logic in the data_pro.py file. Specifically, the kfold.split function returns indices rather than student IDs, but the code appears to treat these indices as if they were student IDs. As a result, there is an unintended overlap between the train_list and test_list, as well as between the valid_list and test_list.

Here is the relevant snippet:

```
for i, (train_list, valid_list) in enumerate(kfold.split(train_valid_list)):
    file_path = f'./assist17/{i}_train_valid_assist17_100_split.pkl'

      with open(file_path, 'wb') as f:
        pickle.dump((train_list, valid_list), f)
```

The issue can be corrected as follows:

```
for i, (train_list, valid_list) in enumerate(kfold.split(train_valid_list)):
    file_path = f'{savepath}/{i}_train_valid_assist17_100_split.pkl'
    with open(file_path, 'wb') as f:
        pickle.dump((np.array(train_valid_list)[train_list], np.array(train_valid_list)[valid_list]), f)

```

**Comment by Oia-10** [comment]
Thank you for raising this issue! I have updated the `data_pro.py` file to correctly handle this behavior and ensure the data splitting is performed as intended. After applying the fix, I reran several baselines, and here are the updated results:

|       | **ASSIST17**              |                     |                     |                     | **ASSIST12**              |                     |                     |                     |
|-------|---------------------------|---------------------|---------------------|---------------------|---------------------------|---------------------|---------------------|---------------------|
|       | **AUC**                   | **ACC**             | **RMSE**            | **R2**              | **AUC**                   | **ACC**             | **RMSE**            | **R2**              |
| **AKT** | 0.7567                    | 0.7069              |0.4354             | 0.1906              | 0.7860                    |0.7630              | 0.4038              | 0.2302             |
| **PKT** | 0.7648 |	0.7127	| 0.4323 |	0.2018	| 0.7699 |	0.7532 |	0.4114 |	0.2009|
| **LPKT** | 0.7856 |	0.7277|	0.4229|	0.2363|	0.7996|	0.7656|	0.3992|	0.2478 |
| **PSKT** | 0.7990 |  	0.7363|  	0.4169|  	0.2573 |  	0.8112 |  	0.7735 |  	0.3933 |  	0.2696 |      

Since all baselines use the same dataset splits, their relative performance results have not changed significantly.

Thank you again for bringing this to my attention!

**Comment by Oia-10** [comment]
Thank you very much for pointing out the errors in our code. I have fixed the data processing part (`data_pro.py`) and will review the entire project code soon to provide the best reading experience for our readers.
